---
- name: Create associated accounts
  hosts: all
  #gather_facts: no
  vars_files:
    - vars/users.yml
      # vault password file: vars/sec-file1

  tasks:
    - name: Create associated user
      user:
        name: "{{ item.name }}"
        shell: /bin/bash
        password: "{{ item.password | password_hash('sha512') }}"
        # password mustn't be plain text which should be hashed by sha512
        # according to /etc/login.defs
        state: present
      loop: "{{ user_info }}"  

    - name: Create associated group
      group:
        name: group1
        gid: 2001
        state: present

- name: Test several file modules
  hosts: all
  #gather_facts: no

  tasks:
    - name: Touch a file and set permissions
      file:
        path: /home/user1/file1
        owner: user1
        group: group1
        mode: 0640
        state: touch
        # Create a new file if the file doesn't exist.

    - name: SELinux type is set to samba_share_t
      file:
        path: /home/user1/file1
        setype: samba_share_t

    - name: SELinux type is persistently set to samba_share_t
      sefcontext:
        target: /home/user1/file1
        setype: samba_share_t
        state: present

    - name: Add a line of text to a file
      lineinfile:
        path: /home/user1/file1
        line: 'Add this line to the file'
        state: present

    - name: Add additional lines to a file
      blockinfile:
        path: /home/user1/file1
        block: |
          First line in the additional block of text
          Second line in the addtional block of text
        state: present  

    - name: stat /etc/passwd
      stat:
        path: /etc/passwd
        checksum_algorithm: sha512
      register: results
      
    - name: Display stat results
      debug:
        #var: results
        msg: "The checksum of the file is {{ results.stat.checksum }}"

