---
- name: Install HAProxy
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - haproxy

- name: Copy haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart_haproxy

- name: Start HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes

- name: Allow HAProxy service through firewalld
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
...    
