---
# tasks file for motd

- name: Deliver motd file
  ansible.builtin.template:
    src: motd.j2  #search from templates/ dir
    dest: /etc/motd.d/rh294
    owner: root
    group: root
    mode: 0444
