# SPDX-License-Identifier: MIT
---
- hosts: all
  tasks:
    - name: "Configure ssh clients"
      include_role:
        name: redhat.rhel_system_roles.ssh
      vars:
        ssh_user: root
        ssh:
          Compression: true
          GSSAPIAuthentication: no
          ControlMaster: auto
          ControlPath: ~/.ssh/.cm%C
          Match:
            - Condition: "final all"
              GSSAPIAuthentication: yes
          Host:
            - Condition: example
              Hostname: example.com
              User: somebody
        ssh_ForwardX11: no
