---
- name: Example with no waiting for cert issuance
  hosts: all
  vars:
    certificate_wait: false
    certificate_requests:
      - name: mycert
        dns: www.example.com
        ca: self-sign
  roles:
    - redhat.rhel_system_roles.certificate
