---
- name: Test SELinux role
  hosts: servera.lab.example.com

  tasks:
    - name: Apply SELinux role
      block:
        - include_role: 
            name: rhel-system-roles.selinux
        - name: Verify selinux_reboot_required variable
          debug:
            msg: selinux_reboot_required is "{{ selinux_reboot_required }}"
      rescue:
        - name: Check for failure for other reasons than required reboot
          fail:
          when: not selinux_reboot_required

        - name: Restart managed host
          reboot:

        - name: Reapply SELinux role to complete roles
          include_role: 
            name: rhel-system-roles.selinux
            
