---
- name: Sample of force handlers keyword
  hosts: all
  force_handlers: yes

  tasks:
    - name: a task which always notifies its handler
      command: /bin/true
      notify:
        - restart web server

    - name: a task which fails because the package doesn't exist
      yum:
        name: notapkg
        state: latest

  handlers:
    - name: restart web server
      service:
        name: httpd
        state: restarted
