---
- name: use motd role playbook
  hosts: serverb.lab.example.com
  # vars:
  #   system_owner: someone@host.example.com

  roles:
    - role: motd
      # vars:
      #  system_owner: someone@host.example.com
      system_owner: someone@host.example.com
