# SPDX-License-Identifier: BSD-3-Clause
---
- hosts: all
  tasks:
    - include_role:
        name: redhat.rhel_system_roles.network
      vars:
        network_connections:
          - name: "{{ network_interface_name1 }}"
            state: up
            type: ethernet
            ip:
              dhcp4: "no"
              auto6: "no"
