---
# Note:
#   1.sefcontext module not found in Ansible Core and execution environment,
#     so don't use this module in playbook.
#   2.run playbook as following command:
#     $ ansible-navigator run -m stdout --vault-password-file=vars/sec-file1 file_modules_demo.yml
- name: Create associated accounts
  hosts: all
  #gather_facts: false
  vars_files:
    - vars/users.yml
      # vault password file: vars/sec-file1

  tasks:
    - name: Create associated user
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /bin/bash
        password: "{{ item.password | password_hash('sha512') }}"
        # password mustn't be plain text which should be hashed by sha512
        # according to /etc/login.defs
        # MUST use password_hash filter to crypt plain text password in Ansible
        state: present
      loop: "{{ user_info }}"  

    - name: Create associated group
      ansible.builtin.group:
        name: group1
        gid: 2100
        state: present

- name: Test several file modules
  hosts: all
  #gather_facts: false

  tasks:
    - name: Touch a file and set permissions
      ansible.builtin.file:
        path: /home/user1/file1
        owner: user1
        group: group1
        mode: 0640
        state: touch
        # create a new file if the file doesn't exist

    - name: SELinux type is set to samba_share_t
      ansible.builtin.file:
        path: /home/user1/file1
        setype: samba_share_t

#    - name: SELinux type is persistently set to samba_share_t
#      sefcontext:
#        target: /home/user1/file1
#        setype: samba_share_t
#        state: present

    - name: Add a line of text to a file
      ansible.builtin.lineinfile:
        path: /home/user1/file1
        line: 'Add this line to the file'
        state: present

    - name: Add additional lines to a file
      ansible.builtin.blockinfile:
        path: /home/user1/file1
        block: |
          First line in the additional block of text
          Second line in the addtional block of text
        state: present  

    - name: stat /etc/passwd
      ansible.builtin.stat:
        path: /etc/passwd
        checksum_algorithm: sha512
      register: results
      
    - name: Display stat results
      ansible.builtin.debug:
        #var: results
        msg: "The checksum of the file is {{ results.stat.checksum }}"
...
