---
# tasks file for apache

- name: Ensure httpd packages are installed
  yum:
    name:
      - httpd
      - php
      - git
      - php-mysqlnd
    state: present

- name: Ensure SELinux allows httpd connections to a remote database
  seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: yes

- name: Ensure httpd service is started and enabled
  service:
    name: httpd
    state: started
    enabled: yes

