---
- name: Disable cockpit and dhcpv6-client service in default zone
  hosts: "{{ targets }}"
  vars:
    firewall:
      - service: [cockpit, dhcpv6-client]
        state: disabled
  roles:
    - redhat.rhel_system_roles.firewall
