---
- name: Erase existing config and enable ssh service
  hosts: "{{ targets }}"

  vars:
    firewall:
      - previous: replaced
      - service: ssh
        state: enabled
  roles:
    - redhat.rhel_system_roles.firewall
