---
# Use the playbook to setup module runtime to test training
# on master which helps to conduct how to build tensorflow image.
# 
# Also run the playbook to prepare tensorflow environment on agent
# node as to run Jenkinsfile from CNN project.
#
- name: Prepare TensorFlow and Flask runtime for CNN module
  hosts: master,jenkins-agent1.lab.example.com
  vars_files:
    - ../vars/all_vars.yml

  tasks:
    - name: Install python3-pip package
      ansible.builtin.dnf:
        name: python3-pip
        state: present
    - name: Create {{ jenkins_pip_conf }} directory
      ansible.builtin.file:
        path: "{{ jenkins_pip_conf }}"
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'
      when: inventory_hostname == 'jenkins-master.lab.example.com'
    - name: Ensure jenkins user existed
      ansible.builtin.user:
        name: jenkins
        state: present
      when: inventory_hostname == 'jenkins-agent1.lab.example.com'
    - name: Create {{ jenkins_local_pip_conf }} directory
      ansible.builtin.file:
        path: "{{ jenkins_local_pip_conf }}"
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'
      when: inventory_hostname == 'jenkins-agent1.lab.example.com'
    - name: Setup pip3 upstream module source for master
      ansible.builtin.copy:
        src: ../files/pip.conf
        dest: "{{ jenkins_pip_conf }}"
        owner: jenkins
        group: jenkins
      when: inventory_hostname == 'jenkins-master.lab.example.com'
    - name: Setup pip3 upstream module source for agent
      ansible.builtin.copy:
        src: ../files/pip.conf
        dest: "{{ jenkins_local_pip_conf }}"
        owner: jenkins
        group: jenkins
      when: inventory_hostname == 'jenkins-agent1.lab.example.com'
    - name: Install TensorFlow and dependency modules
      ansible.builtin.pip:
        name:
          - pysocks
          - tensorflow==2.18.0
          - matplotlib
          #- flask
      become: True
      become_user: jenkins
      # Note: 
      #   $ pip3 install --ignore-installed <module_name>==<version>
    - name: Ensure TensorFlow modules
      ansible.builtin.shell: pip list | grep -e pysocks -e tensorflow -e matplotlib
      register: tf_state
      become: True
      become_user: jenkins
    - name: Verify tf_state variable
      ansible.builtin.debug:
        var: tf_state

