# SPDX-License-Identifier: MIT
---

- name: Restart pmcd
  service:
    name: pmcd
    state: restarted

- name: Restart pmie
  service:
    name: pmie
    state: restarted

- name: Restart pmproxy
  service:
    name: pmproxy
    state: restarted

- name: Restart pmlogger
  service:
    name: pmlogger
    state: restarted
