---
- name: Test multiple Jinja2 lookup plug-ins
  hosts: localhost
  become: false
  gather_facts: no

  tasks:
    ## file plug-in
    - name: lookup function calls file plug-in
      ansible.builtin.debug:
        msg: "Variable hosts is: {{ hosts }}"
      vars:
        # hosts: "{{ lookup('file', '/etc/hosts', '/etc/issue') }}"
        hosts: "{{ query('file', '/etc/hosts', '/etc/issue') }}"
      tags:
        - lookup_query_file

    - name: Transfer YAML file format
      ansible.builtin.debug:
        msg: "Transformation format of file is: {{ my_yaml }}"
      vars:
        my_yaml: "{{ lookup('file', 'user_list.yml') | from_yaml }}"
      # from_yaml filter used to transfer yaml format to structure file  
      tags:
        - lookup_file_from_yaml

    ## template plug-in
    - name: Print "Hello class"
      ansible.builtin.debug:
        msg: "{{ lookup('template', 'mytemplate.j2') }}"
      vars:
        name: class
      tags:
        - lookup_template

    ## pipe, lines plug-in
    - name: Prints the specfied line of some files
      ansible.builtin.debug:
        msg: "{{ item[0] }}"
      loop:
        #- "{{ query('lines', 'cat /etc/services') }}"
        - "{{ query('lines', 'cat /etc/passwd') }}"
        - "{{ query('lines', 'cat /etc/issue') }}"
        - "{{ query('pipe', 'cat /etc/group') }}"
      tags:
        - query_lines_pipe
      
      # Note:
      #   If use DO374 RHAAP2.x course, please ensure files in automation
      #   execution environment, or playbook returns error.

    - name: Verify lookup plugin file ERROR
      ansible.builtin.debug:
        msg: Message is {{ message }}
      vars:
        message: "{{ lookup('file', 'myfile.txt', errors='strict') }}"
      tags:
        - lookup_errors

