---
- name: Test Jinja2 variables
  hosts: localhost
  gather_facts: no
  become: false
  vars:
    my_list:
      - Douglas
      - Marvin
      - Arthur
    my_dict:
      Douglas: Human
      Marvin: Robot
      Arthur: Human
    name: null  
    #name: ~
  
  tasks:
    - name: Confirm that the second list element is "Marvin"
      assert:
        that:
          - my_list[1] == 'Marvin'
          #- my_list[1] == 'Albert'

    - name: Confirm "Marvin" vaule of hash
      assert:
        that:
          - my_dict['Marvin'] == 'Robot'

    - name: Verify name variable is or not defined
      command: echo "name variable is undefined"
      when: name is undefined
      register: name_result

    - name: Display name variable output
      debug:
        var: name_result
