---
- hosts: all

  vars:
    certificate_requests:
      - name: mycert
        dns: www.example.com
        auto_renew: no
        ca: self-sign

  roles:
    - redhat.rhel_system_roles.certificate
