---
- hosts: all

  vars:
    certificate_wait: no
    certificate_requests:
      - name: mycert
        dns: www.example.com
        ca: self-sign

  roles:
    - redhat.rhel_system_roles.certificate
