---
- hosts: all

  vars:
    certificate_requests:
      - name: mycert
        dns: www.example.com
        ca: self-sign
        provider: fake-provider

  roles:
    - redhat.rhel_system_roles.certificate
