[monitoring]
monitoring-server ansible_host=servera

[app_servers]
app-server-1 ansible_host=serverb
app-server-2 ansible_host=serverc

[nodes]
node-1 ansible_host=serverc
node-2 ansible_host=serverd

[all_servers:children]
monitoring
app_servers
nodes
