---
- name: use motd role playbook
  hosts: serverb.lab.example.com
  # gather_facts: yes

  tasks:
    - name: verify managed host cpu architecture
      debug:
        msg: Arch of managed host is {{ ansible_facts['architecture'] }}
     
    - name: test include_role module with when statement
      include_role:
      # import_role:
        name: motd
      vars:
        system_owner: tommy@host.example.com
      # Just vars directive can be under include_role module.
      when: ansible_facts['architecture'] == "x86_64"
      #when: ansible_facts['architecture'] == "amd"
