---
- name: Test multiple Jinja2 lookup plug-ins
  hosts: localhost
  become: false
  gather_facts: no

  tasks:
    ## file plug-in
    - name: lookup function calls file plug-in
      debug:
        msg: "Variable hosts is: {{ hosts }}"
      vars:
        # hosts: "{{ lookup('file', '/etc/hosts', '/etc/issue') }}"
        hosts: "{{ query('file', '/etc/hosts', '/etc/issue') }}"

    - name: Transfer YAML file format
      debug:
        msg: "Transformation format of file is: {{ my_yaml }}"
      vars:
        my_yaml: "{{ lookup('file', 'user_list.yml') | from_yaml }}"
      # from_yaml filter used to transfer yaml format to structure file  


    ## template plug-in
    - name: Print "Hello class"
      debug:
        msg: "{{ lookup('template', 'mytemplate.j2') }}"
      vars:
        name: class


    ## pipe, lines plug-in
    - name: Prints the specfied line of some files
      debug:
        msg: "{{ item[2] }}"
      loop:
        - "{{ query('lines', 'cat /etc/services') }}"
        - "{{ query('lines', 'cat /etc/passwd') }}"
        - "{{ query('lines', 'cat /etc/issue') }}"

    - name: Verify lookup plugin file ERROR
      debug:
        msg: Message is {{ message }}
      vars:
        message: "{{ lookup('file', 'myfile.txt', errors='warn') }}"

