---
- name: Test meta module to verify multiple handlers
  hosts: webservers
  order: reverse_sorted
  become: true

  tasks:
    - name: Install several packages
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
      vars:
        packages:
          - httpd
          - mariadb-server
      notify: restart-srv
      changed_when: true  

    - name: Use meta module to flush handlers
      meta: flush_handlers

  handlers:
    - name: Restart apache web server
      service:
        name: httpd
        state: restarted
        enabled: yes
      listen: restart-srv 
    - name: Restart mariadb database
      service:
        name: mariadb
        state: restarted
        enabled: yes
      listen: restart-srv  
