# SPDX-License-Identifier: MIT
---

- name: Ensure metric log location is configured
  lineinfile:
    path: "{{ __pcp_conf }}"
    regexp: '^PCP_ARCHIVE_DIR='
    line: PCP_ARCHIVE_DIR={{ pcp_archive_dir }}
  notify:
    - restart pmlogger
    - restart pmproxy

- name: Ensure performance metric logging is configured
  template:
    src: pmlogger.defaults.j2
    dest: "{{ __pcp_pmlogger_defaults_path }}"
    mode: 0644
  notify: restart pmlogger

- name: Ensure performance metric logging retention period is set
  template:
    src: pmlogger.timers.j2
    dest: "{{ __pcp_pmlogger_timers_path }}"
    mode: 0644
  notify: restart pmlogger

- name: Ensure performance metric logging is enabled for targeted hosts
  template:
    src: pmlogger.control.j2
    dest: "{{ __pcp_pmlogger_control_path }}/{{ item }}"
    mode: 0644
  loop: "{{ pcp_target_hosts|default([]) }}"
  notify: restart pmlogger

- name: Ensure performance metric logging is running and enabled on boot
  service:
    name: pmlogger
    state: started
    enabled: yes
