---
collections:
  - name: ansible.netcommon

  - name: redhat.rhv
    version: 1.4.1

  - name: community.crypto
    version: 1.9.3

  - name: ansible.controller  

  - name: http://classroom.example.com/content/courses/ansible-tower-3.8.5.tar.gz

  - name: git@git.lab.example.com:student/ansible.tower.git
