---
# tasks file for web_server

- name: Ensure HTTPD packages are present
  yum:
    name: "{{ apache_packages }}"
    state: present

- name: Ensure SELinux is set to allow httpd connections to a remote database
  seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: yes

- name: Ensure HTTPD service is started and enabled
  service:
    name: httpd
    state: started
    enabled: yes

