---
# Note:
#   1.run playbook as following command:
#     $ ansible-navigator run -m stdout \
#       --vault-password-file=vault/sec1 --vault-password-file=vault/sec2 \
#       verify-httpd-pkg.yml
#   2.option --vault-password-file also be used by ansible-navigator command
#     as ansible-playbook   
- name: Test multiple vault variables file
  hosts: all
  gather_facts: false
#  vars_files:
#    - vars/packages.yml
#    - vars/state.yml

  tasks:
    - name: Gather facts manualy
      ansible.builtin.setup:

    - name: Prints various Ansible facts
      ansible.builtin.debug:
        msg: |
          The default IPv4 address of {{ ansible_facts.fqdn }}
          is {{ ansible_facts.default_ipv4.address }}
      # | 与 > 的区别：| 在返回的结果中不带有 \n，而 > 在返回的结果中带有 \n。

#    - name: Verify Apache httpd installed
#      ansible.builtin.yum:
#        name: "{{ package }}"
#        state: "{{ status }}"
...
