# SPDX-License-Identifier: MIT
---
- name: Set up Elasticsearch for use with PCP
  hosts: monitoring

  roles:
    - role: redhat.rhel_system_roles.metrics
      vars:
        metrics_provider: pcp
        metrics_from_elasticsearch: yes
        metrics_into_elasticsearch: yes
