---
- name: Sample of force handlers keyword
  hosts: all
  force_handlers: true

  tasks:
    - name: a task which always notifies its handler
      ansible.builtin.command: /bin/true
#    - name: install Performance Co-Polit(PCP) elements
#      ansible.builtin.dnf:
#        name:
#          - pcp
#          - pcp-gui
#        state: present
      notify:
        - restart web server
        - restart rsyslog service

    - name: a task which fails because the package doesn't exist
      ansible.builtin.yum:
        name: notapkg
        state: latest
      #ignore_errors: true  

  handlers:
    # Use notify list to trigger different handlers as samples,
    # so we don't use loop statement to merge service.
    - name: restart web server
      ansible.builtin.service:
        name: httpd
        state: restarted

    - name: restart rsyslog service
      ansible.builtin.service:
        name: rsyslog
        state: restarted
...        
