---
- name: Config Jenkins Associated Nodes
  hosts: master,agents
  vars_files:
    - ../vars/all_vars.yml
  tags:
    - base_config
    - master_config
    - agent_config

  tasks:
    - name: Install dependent packages
      ansible.builtin.dnf:
        name:
          - fontconfig
          - java-17-openjdk
          - git
          - jq
          - podman
        state: present
    - name: Stop firewalld service
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: False

- name: Deploy Jenkins Master Component
  hosts: master
  vars_files:
    - ../vars/all_vars.yml
  tags:
    - master_config

  tasks:
    - name: Download jenkins rpm package
      ansible.builtin.get_url:
        url: "{{ jenkins_pkg_url }}"
        dest: /tmp
        mode: '0644'
    - name: Import jenkins gpg check file
      ansible.builtin.command: rpm --import {{ jenkins_gpg_url }}
    - name: Install jenkins service
      ansible.builtin.dnf:
        name: /tmp/{{ jenkins_version }}
        state: present
    - name: Start and enable jenkins service
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: True
    - name: Get jenkins service status
      ansible.builtin.command: systemctl status jenkins.service
      register: jkn_status
    - name: Report jenkins service status
      ansible.builtin.debug:
        var: jkn_status

- name: Setup Jenkins SSH Agent
  hosts: agents
  vars_files:
    - ../vars/all_vars.yml
  tags:
    - agent_config

  tasks:
    - name: Create jenkins user account as ssh agent user
      ansible.builtin.user:
        name: "{{ jenkins_user }}"
        password: "{{ jenkins_password | password_hash('sha512') }}"
        shell: /bin/bash
    - name: Create jenkins ssh agent data directory
      ansible.builtin.file:
        path: "{{ jenkins_agent_dir }}"
        state: directory
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_group }}"
    - name: Setup jenkins ssh agent SSH directory
      ansible.builtin.file:
        path: /home/jenkins/.ssh
        state: directory
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_group }}"
        mode: '0700'
    - name: Generate jenkins authorized_keys file
      ansible.builtin.file:
        path: /home/jenkins/.ssh/authorized_keys
        state: touch
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_group }}"
        mode: '0600'

