---
# Note:
#   This demo including motd role in current directory should be runned as following:
#   $ ansible-navigator run -m stdout motd_role_demo.yml
- name: use motd role playbook
  hosts: webserver2
  #vars:
  #  system_owner: someone@host.example.com  #变量优先级测试1

  roles:
    - role: motd
      #vars:
      #  system_owner: someone@host.example.com  #变量优先级测试2
      #system_owner: someone@host.example.com  #变量优先级测试3
...
