---
# Note:
#   $ ansible-galaxy collection install -p collections/ -r collections/requirements.yml
#   # install collections according to requirements.yml

collections:
  - name: http://content.example.com/redhat-rhel_system_roles-1.21.1.tar.gz
    # download from internal webserver and install collection tarball
    # Note: please store redhat-rhel_system_roles-1.21.1.tar.gz tarball in foundation0 /content directory
  - name: community.general
    version: 7.0.0
    # download and install from https://galaxy.ansible.com/community/general
