---
- name: Deploy apache web services
  hosts: webservers
  become: false

  tasks:
    - block:
      - name: Ensure httpd is installed
        ansible.builtin.yum:
          name: httpd
          state: installed
      - name: Start and enable webserver
        ansible.builtin.service:
          name: httpd
          state: started
          enabled: yes
      - name: Create new index.html
        ansible.builtin.file:
          path: /var/www/html/index.html
          state: touch
      - name: Insert hello content into index.html
        ansible.builtin.lineinfile:
          path: /var/www/html/index.html
          line: "Hello DO447 candidates!"
      - name: Enable httpd service in firewalld
        ansible.posix.firewalld:
          service: http
          permanent: yes
          state: enabled
          immediate: yes
      become: true

    - name: Test website from itself, do not become
      ansible.builtin.uri:
        url: http://{{ ansible_host }}  #魔法变量
        return_content: yes
      register: webpage
      failed_when: webpage.status != 200
      ignore_errors: yes
      #若返回码不为 200 时，将该任务设置为 failed。

    - name: Check webpage variable content
      ansible.builtin.debug:
        var: webpage

