---
- name: Test meta module to verify multiple handlers
  hosts: webservers
  order: reverse_sorted
  become: true

  tasks:
    - name: Install several packages
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
      vars:
        packages:
          - httpd
          - mariadb-server
      notify: restart-srv
      changed_when: true  

      # 执行 handlers 的方式：
      #   方法 1：notify 指令中定义的名称必须与 handlers 中定义的名称相同
      #   方法 2：使用 meta 模块时，notify 指令使用的名称必须与 handlers 中的保持一致，
      #           并且将强制刷新上一个任务中 notify 指令的通知列表。
      #   方法 3：使用 handlers 中的 listen 指令订阅 notify 指令的通知。

  handlers:
    - name: Restart apache web server
      service:
        name: httpd
        state: restarted
        enabled: yes
      listen: restart-srv 
    - name: Restart mariadb database
      service:
        name: mariadb
        state: restarted
        enabled: yes
      listen: restart-srv  
