---
- name: Example play using tagging
  hosts:
    - servera.lab.example.com
    - serverb.lab.example.com

  tasks:
    - name: httpd is installed
      ansible.builtin.yum:
        name: httpd
        state: latest
      tags: 
        - webserver

    - name: postfix is installed
      ansible.builtin.yum:
        name: postfix
        state: latest

