---
- name: Generate certificates
  include_role:
    name: redhat.rhel_system_roles.certificate
  vars:
    certificate_requests: "{{ logging_certificates }}"
  when: logging_certificates | length > 0
