---
- name: Deploy Apache HTTPD Web Server
  hosts: managed_nodes,!servera.lab.example.com

  tasks:
    - name: install httpd packages
      ansible.builtin.yum:
        name: httpd-2.4.51-7.el9_0.x86_64
        state: present
    - name: start and enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
    - name: allow web port access
      ansible.posix.firewalld:
        zone: public
        service: http
        permanent: true
        state: enabled
        immediate: true

- name: Storage info collect
  hosts: servera.lab.example.com

  tasks:
    - name: collect lvm infomation
      ansible.builtin.command: /sbin/lvs
...
