---
- name: Test ansible automation execution environments
  hosts: servera.lab.example.com
  
  tasks:
    - name: Create new user
      ansible.builtin.user:
        name: sysadmin
        uid: 2000
        state: present
        group: wheel
        append: yes

    - name: Test firewalld module in ansible 2.9
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: yes
        immediate: yes  
