---
- name: Deploy Apache HTTPD Web Server
  hosts: managed_nodes,!servera.lab.example.com
  gather_facts: no
  vars:
    package: httpd-2.4.51-7.el9_0.x86_64

  tasks:
    - name: install httpd packages
      ansible.builtin.yum:
        name: "{{ package }}"
        state: present
    - name: start and enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
    - name: allow web port access
      ansible.posix.firewalld:
        zone: public
        service: http
        permanent: yes
        state: enabled
        immediate: yes

- name: Storage info collect        
  hosts: servera.lab.example.com
  gather_facts: no

  tasks:
    - name: collect lvm infomation
      ansible.builtin.command: /sbin/lvs
      register: lvs_result
    - name: verify lvs result
      ansible.builtin.debug:
        var: lvs_result
      
