---
- name: Test custom fact variable
  hosts: servera.lab.example.com
  gather_facts: no

  tasks:
    - name: Create /etc/ansible/facts.d directory
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: directory
        mode: '0755'

    - name: Copy custom fact variable file
      ansible.builtin.copy:
        src: custom.fact
        dest: /etc/ansible/facts.d
        owner: root
        group: root
        mode: '0644'

    - name: Collect facts
      ansible.builtin.setup:
      register: setup_results

    - name: Verify setup_results
      ansible.builtin.debug:
        msg: "Custome fact variable is: {{ ansible_local }}"
