---
# Usage of loop, register and debug
- name: Loop Register Test
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Looping Echo Task
      ansible.builtin.shell: "echo This is my item: {{ item }}"
      loop:
        - one
        - two
      register: echo_results

    - name: Show echo_results variable
      ansible.builtin.debug:
        var: echo_results

    - name: Show stdout from the previous task.
      ansible.builtin.debug:
        msg: "STOUT from previous task: {{ item.stdout }}"
      loop: "{{ echo_results['results'] }}"

