---
- name: Test delegation tasks
  hosts: servera.lab.example.com
  become: false
  tags:
    - delegate_tasks

  tasks:
    - name: "{{ inventory_hostname }}: get system information"
      ansible.builtin.command: uname -a
      register: inventory_server_info

    - name: "{{ inventory_hostname }}: display system information"
      dansible.builtin.ebug:
        msg: "{{ inventory_server_info }}"

    - name: Delegate system information to other host
      ansible.builtin.command: uname -a
      delegate_to: serverb.lab.example.com
      register: delegate_server_info

    - name: Display delegate system information
      ansible.builtin.debug:
        msg: "{{ delegate_server_info }}"

- name: Test delegation facts
  hosts: servera.lab.example.com
  gather_facts: no
  tags:
    - delegate_facts

  tasks:
    - name: Set a fact in delegated task for serverb
      ansible.builtin.set_fact:
        myfact: Where am I set?
      delegate_to: serverb.lab.example.com
      delegate_facts: true

    - name: Display the facts from serverb.lab.example.com
      ansible.builtin.debug:
        msg: "{{ hostvars['serverb.lab.example.com']['myfact'] }}"
      # use magic variable to verify delegation fact

