---
__ssh_packages: ['openssh-client']
__ssh_defaults:
  Include: /etc/ssh/ssh_config.d/*.conf
  Host:
    - Condition: "*"
      SendEnv: LANG LC_*
      HashKnownHosts: yes
      GSSAPIAuthentication: yes
