---
- name: Populate users and groups
  hosts: all
  gather_facts: yes

  tasks:
    - name: Load group information
      set_fact:
        user_groups: "{{ lookup('file', 'groups.yml') | from_yaml }}"
        # lookup function used with from_yaml filter to return list
      register: get_yaml_list

    # modified by hualf
    - name: Display customized fact user_groups
      debug:
        var: get_yaml_list

    - name: Create groups
      group:
        name: "{{ item.name }}"
        state: present
      loop: "{{ user_groups }}"

    - name: Create users
      user:
        name: "{{ item }}"
        password: "{{ password | password_hash('sha512') }}"
        update_password: on_create
        state: present
      vars:
        password: "{{ lookup('password', 'credentials/' + item + ' length=9' ) }}"
      loop: "{{ query('lines', 'cat users.txt') }}" 

    - name: Add users to groups
      user:
        name: '{{ item.1 }}'
        groups: "{{ item.0.name }}"
        append: yes
      loop: "{{ user_groups | subelements('members', 'skip_missing=true') }}"
