---
- name: Deploy Apache HTTPD Web Server
  hosts: managed_nodes,!webserver1
  gather_facts: false
  vars:
    package: httpd-2.4.51-7.el9_0.x86_64

  tasks:
    - name: install {{ package }} packages
      ansible.builtin.dnf:
        name: "{{ package }}"
        state: present
    - name: start and enable {{ package }} service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
    - name: allow web port access
      ansible.posix.firewalld:
        zone: public
        service: http
        permanent: true
        state: enabled
        immediate: true

- name: Storage info collect        
  hosts: webserver1
  gather_facts: false

  tasks:
    - name: collect lvm infomation
      ansible.builtin.command: /sbin/lvs
      register: lvs_result
    - name: verify lvs result
      ansible.builtin.debug:
        var: lvs_result
...      
