---
- name: Test custom fact variable
  hosts: webserver1
  remote_user: root
  gather_facts: false

  tasks:
    - name: Collect facts
      ansible.builtin.setup:
      #register: setup_results

    - name: Setup temp variable
      ansible.builtin.set_fact:
        first_fact: redhat
        second_fact: suse
        third_fact: debian

    - name: Assert fact variable
      ansible.builtin.assert:
        that:
          - first_fact == 'redhat'  #断言判断变量的值是否正确

    - name: Verify setup_results
      ansible.builtin.debug:
        msg: "Custome fact variable is: {{ ansible_local }}, and copied_var is {{ copied_var }}"
      vars:
        copied_var: "{{ second_fact }}"  #使用 set_fact 模块设置中间变量传递给其他变量   
